# This is a basic workflow to help you get started with Actions

name: CI

on: [push]
jobs:
  To-Zip:
    runs-on: ubuntu-latest
    steps:
      - name: action-zip
        # You may pin to the exact commit or the version.
        # uses: montudor/action-zip@0852c26906e00f8a315c704958823928d8018b28
        uses: montudor/action-zip@v1.0.0

