# This is a basic workflow to help you get started with Actions

name: CI

on: [push]
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: Libs/ LC-GroupLoot.toc lc grouploot.lua
          dest: LC-GroupLoot.zip

